import type { Metadata, Viewport } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import '@/styles/globals.scss';
import styles from '@/styles/layout.module.scss';

const notosans = Noto_Sans_KR({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notosans.className}>
        <div className={styles.contents}>{children}</div>
      </body>
    </html>
  );
}
